Problem: nightly-2017-03-17 appears to be broken (again)
```
$ cargo --version
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Solution: switch to nightly-2017-03-14