Problem: server hangs in some subscription/sending scenarios
```shell
$ ./target/debug/pumpkindb-term
Connected to PumpkinDB at 127.0.0.1:9981
To send an expression, end it with `.`
Type \h for help.
PumpkinDB> "a" SUBSCRIBE "b" "a" SEND.
thread 'main' panicked at 'Incomplete(Size(99))', pumpkindb_term/src/main.rs:178
note: Run with `RUST_BACKTRACE=1` for a backtrace.
$ ./target/debug/pumpkindb-term
Connected to PumpkinDB at 127.0.0.1:9981
To send an expression, end it with `.`
Type \h for help.
PumpkinDB> 1.
0x01
PumpkinDB> "a" SUBSCRIBE "b" "a" SEND.
thread 'main' panicked at 'Incomplete(Size(99))', pumpkindb_term/src/main.rs:178
note: Run with `RUST_BACKTRACE=1` for a backtrace.
$ ./target/debug/pumpkindb-term
Connected to PumpkinDB at 127.0.0.1:9981
To send an expression, end it with `.`
Type \h for help.
PumpkinDB> 1.
^C
```

Solution: map subscriptions not to tokens, but uuids, since tokens
are re-usable.

Make sure the subscription receiver is re-registered for polling again.

Also, hook unsubscriptions in so they actually work.

Fixes #210